"""
Canonical aircraft operational profiles for feasibility and ranking.

Brochure NM is reference-only; feasibility uses ``practical_nm`` baseline.
"""

from __future__ import annotations

from typing import Any, Dict

AIRCRAFT_PROFILES: Dict[str, Dict[str, Any]] = {
    "Citation CJ2": {
        "category": "light",
        "brochure_nm": 1700,
        "practical_nm": 1400,
        "pax_typical": 6,
        "pax_max_long_range": 6,
        "runway_ft": 3500,
        "hot_high_score": 0.45,
        "short_field_score": 0.7,
        "operating_index": 0.35,
        "cabin_score": 0.45,
        "baggage_score": 0.4,
        "dispatch_score": 0.75,
        "resale_score": 0.7,
        "pilot_workload": 0.85,
        "ownership_efficiency": 0.8,
    },
    "Citation CJ4": {
        "category": "light",
        "brochure_nm": 2100,
        "practical_nm": 1750,
        "pax_typical": 7,
        "pax_max_long_range": 7,
        "runway_ft": 3600,
        "hot_high_score": 0.5,
        "short_field_score": 0.75,
        "operating_index": 0.42,
        "cabin_score": 0.55,
        "baggage_score": 0.5,
        "dispatch_score": 0.78,
        "resale_score": 0.72,
        "pilot_workload": 0.82,
        "ownership_efficiency": 0.78,
    },
    "Phenom 300E": {
        "category": "light",
        "brochure_nm": 2010,
        "practical_nm": 1584,
        "pax_typical": 7,
        "pax_max_long_range": 7,
        "runway_ft": 3800,
        "hot_high_score": 0.48,
        "short_field_score": 0.72,
        "operating_index": 0.4,
        "cabin_score": 0.52,
        "baggage_score": 0.45,
        "dispatch_score": 0.76,
        "resale_score": 0.7,
        "pilot_workload": 0.84,
        "ownership_efficiency": 0.8,
    },
    "Citation Latitude": {
        "category": "super-midsize",
        "brochure_nm": 2700,
        "practical_nm": 2300,
        "pax_typical": 8,
        "pax_max_long_range": 8,
        "runway_ft": 3900,
        "hot_high_score": 0.62,
        "short_field_score": 0.68,
        "operating_index": 0.55,
        "cabin_score": 0.72,
        "baggage_score": 0.65,
        "dispatch_score": 0.82,
        "resale_score": 0.8,
        "pilot_workload": 0.75,
        "ownership_efficiency": 0.72,
    },
    "Citation Longitude": {
        "category": "super-midsize",
        "brochure_nm": 3500,
        "practical_nm": 3000,
        "pax_typical": 8,
        "pax_max_long_range": 10,
        "runway_ft": 4100,
        "hot_high_score": 0.64,
        "short_field_score": 0.66,
        "operating_index": 0.58,
        "cabin_score": 0.78,
        "baggage_score": 0.7,
        "dispatch_score": 0.84,
        "resale_score": 0.82,
        "pilot_workload": 0.72,
        "ownership_efficiency": 0.7,
    },
    "Praetor 600": {
        "category": "super-midsize",
        "brochure_nm": 4000,
        "practical_nm": 3400,
        "pax_typical": 8,
        "pax_max_long_range": 9,
        "runway_ft": 4100,
        "hot_high_score": 0.58,
        "short_field_score": 0.6,
        "operating_index": 0.58,
        "cabin_score": 0.78,
        "baggage_score": 0.7,
        "dispatch_score": 0.8,
        "resale_score": 0.76,
        "pilot_workload": 0.7,
        "ownership_efficiency": 0.68,
    },
    "Challenger 350": {
        "category": "super-midsize",
        "brochure_nm": 3200,
        "practical_nm": 2700,
        "pax_typical": 9,
        "pax_max_long_range": 9,
        "runway_ft": 4500,
        "hot_high_score": 0.65,
        "short_field_score": 0.55,
        "operating_index": 0.62,
        "cabin_score": 0.8,
        "baggage_score": 0.75,
        "dispatch_score": 0.88,
        "resale_score": 0.85,
        "pilot_workload": 0.72,
        "ownership_efficiency": 0.7,
    },
    "Challenger 650": {
        "category": "large",
        "brochure_nm": 4000,
        "practical_nm": 3500,
        "pax_typical": 10,
        "pax_max_long_range": 11,
        "runway_ft": 4800,
        "hot_high_score": 0.7,
        "short_field_score": 0.45,
        "operating_index": 0.78,
        "cabin_score": 0.88,
        "baggage_score": 0.82,
        "dispatch_score": 0.86,
        "resale_score": 0.82,
        "pilot_workload": 0.55,
        "ownership_efficiency": 0.58,
    },
    "Challenger Longitude": {
        "category": "large",
        "brochure_nm": 4300,
        "practical_nm": 3600,
        "pax_typical": 12,
        "pax_max_long_range": 11,
        "runway_ft": 5000,
        "hot_high_score": 0.68,
        "short_field_score": 0.4,
        "operating_index": 0.82,
        "cabin_score": 0.9,
        "baggage_score": 0.85,
        "dispatch_score": 0.84,
        "resale_score": 0.8,
        "pilot_workload": 0.5,
        "ownership_efficiency": 0.52,
    },
    "Gulfstream G280": {
        "category": "super-midsize",
        "brochure_nm": 3600,
        "practical_nm": 3000,
        "pax_typical": 10,
        "pax_max_long_range": 10,
        "runway_ft": 4800,
        "hot_high_score": 0.66,
        "short_field_score": 0.5,
        "operating_index": 0.7,
        "cabin_score": 0.82,
        "baggage_score": 0.78,
        "dispatch_score": 0.84,
        "resale_score": 0.8,
        "pilot_workload": 0.65,
        "ownership_efficiency": 0.62,
    },
    "Falcon 2000": {
        "category": "large",
        "brochure_nm": 3500,
        "practical_nm": 3000,
        "pax_typical": 10,
        "pax_max_long_range": 10,
        "runway_ft": 4500,
        "hot_high_score": 0.68,
        "short_field_score": 0.52,
        "operating_index": 0.72,
        "cabin_score": 0.85,
        "baggage_score": 0.8,
        "dispatch_score": 0.83,
        "resale_score": 0.78,
        "pilot_workload": 0.58,
        "ownership_efficiency": 0.6,
    },
    "Falcon 7X": {
        "category": "large",
        "brochure_nm": 5900,
        "practical_nm": 5000,
        "pax_typical": 12,
        "pax_max_long_range": 12,
        "runway_ft": 5000,
        "hot_high_score": 0.72,
        "short_field_score": 0.38,
        "operating_index": 0.88,
        "cabin_score": 0.9,
        "baggage_score": 0.85,
        "dispatch_score": 0.85,
        "resale_score": 0.8,
        "pilot_workload": 0.45,
        "ownership_efficiency": 0.5,
    },
    "Falcon 8X": {
        "category": "ultra-long",
        "brochure_nm": 6450,
        "practical_nm": 5600,
        "pax_typical": 12,
        "pax_max_long_range": 13,
        "runway_ft": 5200,
        "hot_high_score": 0.74,
        "short_field_score": 0.32,
        "operating_index": 0.92,
        "cabin_score": 0.92,
        "baggage_score": 0.88,
        "dispatch_score": 0.86,
        "resale_score": 0.82,
        "pilot_workload": 0.42,
        "ownership_efficiency": 0.48,
    },
    "Gulfstream G650ER": {
        "category": "ultra-long",
        "brochure_nm": 7500,
        "practical_nm": 6300,
        "pax_typical": 14,
        "pax_max_long_range": 14,
        "runway_ft": 5500,
        "hot_high_score": 0.76,
        "short_field_score": 0.28,
        "operating_index": 1.0,
        "cabin_score": 0.95,
        "baggage_score": 0.9,
        "dispatch_score": 0.9,
        "resale_score": 0.88,
        "pilot_workload": 0.4,
        "ownership_efficiency": 0.42,
    },
    "Gulfstream G650": {
        "category": "ultra-long",
        "brochure_nm": 7000,
        "practical_nm": 6000,
        "pax_typical": 14,
        "pax_max_long_range": 14,
        "runway_ft": 5500,
        "hot_high_score": 0.76,
        "short_field_score": 0.28,
        "operating_index": 1.0,
        "cabin_score": 0.95,
        "baggage_score": 0.9,
        "dispatch_score": 0.9,
        "resale_score": 0.88,
        "pilot_workload": 0.4,
        "ownership_efficiency": 0.42,
    },
    "Gulfstream G700": {
        "category": "ultra-long",
        "brochure_nm": 7500,
        "practical_nm": 6400,
        "pax_typical": 15,
        "pax_max_long_range": 15,
        "runway_ft": 5600,
        "hot_high_score": 0.78,
        "short_field_score": 0.26,
        "operating_index": 1.08,
        "cabin_score": 0.97,
        "baggage_score": 0.92,
        "dispatch_score": 0.91,
        "resale_score": 0.87,
        "pilot_workload": 0.38,
        "ownership_efficiency": 0.4,
    },
    "Global 6500": {
        "category": "ultra-long",
        "brochure_nm": 6600,
        "practical_nm": 5800,
        "pax_typical": 13,
        "pax_max_long_range": 14,
        "runway_ft": 5400,
        "hot_high_score": 0.75,
        "short_field_score": 0.30,
        "operating_index": 0.96,
        "cabin_score": 0.94,
        "baggage_score": 0.89,
        "dispatch_score": 0.87,
        "resale_score": 0.84,
        "pilot_workload": 0.41,
        "ownership_efficiency": 0.44,
    },
    "Global 7500": {
        "category": "ultra-long",
        "brochure_nm": 7700,
        "practical_nm": 6600,
        "pax_typical": 14,
        "pax_max_long_range": 14,
        "runway_ft": 5800,
        "hot_high_score": 0.78,
        "short_field_score": 0.25,
        "operating_index": 1.05,
        "cabin_score": 0.96,
        "baggage_score": 0.92,
        "dispatch_score": 0.88,
        "resale_score": 0.86,
        "pilot_workload": 0.38,
        "ownership_efficiency": 0.4,
    },
    "Learjet 75": {
        "category": "light",
        "brochure_nm": 2000,
        "practical_nm": 1650,
        "pax_typical": 7,
        "pax_max_long_range": 7,
        "runway_ft": 3800,
        "hot_high_score": 0.48,
        "short_field_score": 0.72,
        "operating_index": 0.48,
        "cabin_score": 0.58,
        "baggage_score": 0.52,
        "dispatch_score": 0.74,
        "resale_score": 0.65,
        "pilot_workload": 0.8,
        "ownership_efficiency": 0.75,
    },
    "Pilatus PC-24": {
        "category": "light",
        "brochure_nm": 2200,
        "practical_nm": 1900,
        "pax_typical": 8,
        "pax_max_long_range": 8,
        "runway_ft": 2900,
        "hot_high_score": 0.72,
        "short_field_score": 0.95,
        "operating_index": 0.4,
        "cabin_score": 0.62,
        "baggage_score": 0.68,
        "dispatch_score": 0.8,
        "resale_score": 0.78,
        "pilot_workload": 0.78,
        "ownership_efficiency": 0.82,
    },
    "Pilatus PC-12": {
        "category": "turboprop",
        "brochure_nm": 1800,
        "practical_nm": 1500,
        "pax_typical": 8,
        "pax_max_long_range": 8,
        "runway_ft": 2600,
        "hot_high_score": 0.8,
        "short_field_score": 0.98,
        "operating_index": 0.28,
        "cabin_score": 0.5,
        "baggage_score": 0.55,
        "dispatch_score": 0.82,
        "resale_score": 0.75,
        "pilot_workload": 0.88,
        "ownership_efficiency": 0.88,
    },
}
