#!/usr/bin/env python3
"""Generate PHASE56_DATA_UTILIZATION_REPORT.md from broker_certify samples."""

from __future__ import annotations

import statistics
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from tests.e2e.broker_certification_helpers import broker_certify  # noqa: E402


TAIL_QUERIES = [
    "Who owns N807JS?",
    "Show me N650GS",
    "Tell me about N525AB",
]
COMPARISON_QUERIES = ["G280 vs Longitude", "G650 vs G700"]
LISTING_QUERIES = ["2020 Latitude asking 18M", "2018 Challenger 350 asking 17.9M"]
MISSION_QUERIES = ["8 passengers New York to Tokyo nonstop", "7 passengers Boston to Denver"]


def _rate(pass_count: int, total: int) -> str:
    if total == 0:
        return "n/a"
    return f"{100.0 * pass_count / total:.1f}%"


def _run():
    tail_pass = tail_total = 0
    comp_pass = comp_total = 0
    listing_pass = listing_total = 0
    mission_pass = mission_total = 0
    util_pcts: list[float] = []

    lines = [
        "# Phase 56 — Data Utilization Report",
        "",
        "Generated by `scripts/generate_phase56_report.py` (layers path, observability + fact rendering).",
        "",
    ]

    lines.append("## Tail fact utilization")
    for q in TAIL_QUERIES:
        ans, du, _ = broker_certify(q, prefer_e2e=False)
        flow = du.get("fact_flow") or {}
        sel = int(flow.get("selected_facts") or 0)
        ren = int(flow.get("rendered_facts") or 0)
        tail_total += 1
        ok = (sel == 0) or ren > 0
        if ok and sel > 0:
            import re

            ok = not re.search(r"(?is)send\s+me\s+(?:the\s+)?listing\s+package", ans)
        tail_pass += int(ok)
        lines.append(f"- `{q}`: selected={sel} rendered={ren} pass={ok}")
    lines.append(f"\n**tail_fact_utilization_rate:** {_rate(tail_pass, tail_total)}\n")

    lines.append("## Comparison fact-first")
    for q in COMPARISON_QUERIES:
        ans, du, _ = broker_certify(q, prefer_e2e=False)
        comp_total += 1
        bad = "if i were buying today" in ans.lower()
        ok = not bad and ("range" in ans.lower() or "cabin" in ans.lower())
        comp_pass += int(ok)
        lines.append(f"- `{q}`: pass={ok}")
    lines.append(f"\n**comparison_fact_first_rate:** {_rate(comp_pass, comp_total)}\n")

    lines.append("## Listing parse success")
    for q in LISTING_QUERIES:
        ans, du, _ = broker_certify(q, prefer_e2e=False)
        audit = du.get("listing_parse_audit") or {}
        listing_total += 1
        ok = bool(audit.get("parse_success"))
        listing_pass += int(ok)
        lines.append(
            f"- `{q}`: parse_success={ok} model={audit.get('detected_model')} "
            f"year={audit.get('detected_year')} price={audit.get('detected_price')}"
        )
    lines.append(f"\n**listing_parse_success_rate:** {_rate(listing_pass, listing_total)}\n")

    lines.append("## Mission feasibility")
    for q in MISSION_QUERIES:
        ans, du, _ = broker_certify(q, prefer_e2e=False)
        mission_total += 1
        ok = du.get("mission_feasibility_checked") is True
        if "tokyo" in q.lower():
            ok = ok and bool(du.get("mission_infeasible_models"))
        mission_pass += int(ok)
        lines.append(f"- `{q}`: checked={du.get('mission_feasibility_checked')} pass={ok}")
    lines.append(f"\n**mission_feasibility_pass_rate:** {_rate(mission_pass, mission_total)}\n")

    lines.append("## Retrieval utilization distribution")
    for group_name, queries in (
        ("tail", TAIL_QUERIES),
        ("comparison", COMPARISON_QUERIES),
        ("listing", LISTING_QUERIES),
        ("mission", MISSION_QUERIES),
    ):
        for q in queries:
            _, du, _ = broker_certify(q, prefer_e2e=False)
            pct = du.get("retrieval_utilization_pct")
            if pct is not None:
                util_pcts.append(float(pct))
    if util_pcts:
        lines.append(f"- samples: {len(util_pcts)}")
        lines.append(f"- min: {min(util_pcts):.1f}%")
        lines.append(f"- median: {statistics.median(util_pcts):.1f}%")
        lines.append(f"- max: {max(util_pcts):.1f}%")
        low = sum(1 for p in util_pcts if p < 50.0)
        lines.append(f"- below 50%: {low} ({100.0 * low / len(util_pcts):.1f}%)")
    else:
        lines.append("- no utilization samples")

    out = BACKEND / "reports" / "PHASE56_DATA_UTILIZATION_REPORT.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    _run()
